---
- name: Deploy Wazuh Stack on Docker Swarm
  hosts: wazuh_nodes
  tasks:

    - name: Ensure Docker Swarm is initialized
      community.docker.docker_swarm:
        state: present

    - name: Run indexer certificate generator
      community.docker.docker_compose_v2:
        files:
          - generate-indexer-certs.yml
        state: present
        recreate: always
        services:
          - generator
        project_src: ../stack/single-node


    - name: Deploy Wazuh stack
      community.docker.docker_stack:
        state: present
        name: wazuh-stack
        compose:
          - ../stack/single-node/docker-compose.yml
