---
- name: Use existing SSH key from home
  hosts: localhost
  gather_facts: false
  vars:
    home_ssh_dir: "{{ lookup('env','HOME') }}/.ssh"
    ssh_key_name: "id_rsa"   # change if your key has a different name
    ssh_key_path: "{{ home_ssh_dir }}/{{ ssh_key_name }}"

  tasks:
    - name: Ensure ~/.ssh exists
      ansible.builtin.file:
        path: "{{ home_ssh_dir }}"
        state: directory
        mode: "0700"

    - name: Check if SSH key exists
      ansible.builtin.stat:
        path: "{{ ssh_key_path }}"
      register: ssh_key_stat

    - name: Fail if SSH key does not exist
      ansible.builtin.fail:
        msg: "SSH key {{ ssh_key_path }} not found!"
      when: not ssh_key_stat.stat.exists

    - name: Debug - show SSH key path
      debug:
        msg: "Using existing SSH key at {{ ssh_key_path }}"
