---
- name: genreate ssl for signing wazuh stack services
  hosts: main_node
  tasks:
    - name: Gather local UID/GID
      ansible.builtin.set_fact:
        my_uid: "{{ lookup('pipe', 'id -u') }}"
        my_gid: "{{ lookup('pipe', 'id -g') }}"

    - name: Create .env for Compose
      copy:
        dest: ../stack/.env
        content: |
          MY_UID={{ my_uid }}
          MY_GID={{ my_gid }}

    - name: Run indexer certificate generator
      community.docker.docker_compose_v2:
        files:
          - generate-indexer-certs.yml
        state: present
        services:
          - generator
        project_src: ../stack/
