name: CI/CD Pipeline

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Selenium tests
        run: |
          chmod +x ./test.sh
          ./test.sh

  # deploy:
  #   needs: build-and-test
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: self-hosted
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v4
  #
  #     - name: executing run.sh script for deployement
  #       run: |
  #         chmod +x ./run.sh
  #         ./run.sh
